// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ88pClUrvMDAHNGW0PSZg8JSU3dpLh5Q',
    appId: '1:208229722099:web:a5257f5e97eeb85028d486',
    messagingSenderId: '208229722099',
    projectId: 'triplexa-7835a',
    authDomain: 'triplexa-7835a.firebaseapp.com',
    storageBucket: 'triplexa-7835a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCeOW435DcMwcFJwvDUqN5Xjpv0yglpgs',
    appId: '1:208229722099:android:6099fc78a71a896b28d486',
    messagingSenderId: '208229722099',
    projectId: 'triplexa-7835a',
    storageBucket: 'triplexa-7835a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaLAuU8sH6EFA83Imyn2CWJ57y3vay4ME',
    appId: '1:208229722099:ios:e6f2e80ce2cf035328d486',
    messagingSenderId: '208229722099',
    projectId: 'triplexa-7835a',
    storageBucket: 'triplexa-7835a.firebasestorage.app',
    iosBundleId: 'com.triplexa.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaLAuU8sH6EFA83Imyn2CWJ57y3vay4ME',
    appId: '1:208229722099:ios:f19a4b786c87ed5228d486',
    messagingSenderId: '208229722099',
    projectId: 'triplexa-7835a',
    storageBucket: 'triplexa-7835a.firebasestorage.app',
    iosBundleId: 'com.example.triplexa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJ88pClUrvMDAHNGW0PSZg8JSU3dpLh5Q',
    appId: '1:208229722099:web:e293926d6115cecd28d486',
    messagingSenderId: '208229722099',
    projectId: 'triplexa-7835a',
    authDomain: 'triplexa-7835a.firebaseapp.com',
    storageBucket: 'triplexa-7835a.firebasestorage.app',
  );
}
